### ISSUE TITLE
Tp1

### ISSUE THREAD

**Issue by matiashamide** [inaaranza/2020_K2031_Grupo_3#2]
Buenas @santiagoferreiros,
tuvimos problemas con el archivo de salida, la resolucion se escribe en digitos  en un archivo .txt que no se entienden
[Tp1.txt](https://github.com/inaaranza/2020_K2031_Grupo_3/files/4500522/Tp1.txt)

**Comment by santiagoferreiros** [comment]
Estimados,

Veo algunas cosas que no están bien. Tengan cuidado al comprar los caracteres con punteros a cadenas de caracteres.

Por ejemplo

        while(nro!=delimitador && estado!=ERROR)

nro es de tipo char
delimitador es de tipo char* (puntero a char)

No pueden compararse. Yo les recomiendo que directamente pongan nro!=','
Total el delimitador siempre es el mismo, no es necesario ponerlo dentro de un puntero.

**Comment by santiagoferreiros** [comment]
if(nro!=TT[10][10])  
                
TT[10][10] está fuera del rango de la definición de la matriz. Cuidado con eso.

**Comment by santiagoferreiros** [comment]
En la parte de la función colum

  case 1: for(int i=1;i<=7;i++)
        {
            if(nro==c1[i])
            {
                return c1[i];
            }
            else
            {
                return -1;
            }

Siempre va a salir del for en la primera iteración. Además no devuelve el número de columna sino el caracter que coincidió.

**Comment by santiagoferreiros** [comment]
Finalmente el código que levante no genera un archivo de salida.

Por favor revisar @matiashamide @juliiig @sabrivg @inaaranza @AleSanj
