### ISSUE TITLE
Entrega Trabajo Práctico N°1

### ISSUE THREAD

**Issue by sabrivg** [inaaranza/2020_K2031_Grupo_3#4]
Solicito corrección del trabajo practico: @santiagoferreiros

**Comment by santiagoferreiros** [comment]
Estimados,

El trabajo está aprobado =)
Nota: 8

En los switch pueden utilizar un intervalo de valores, sin indicarlos uno por uno. 
Es decir uno puede poner 'a' ... 'f'

En el archivo de salida, va diciendo si es DECIMAL, OCTAL, etc pero no hace referencia a que cadena de refiere. Les debería haber quedado algo así

123   Decimal
018   Octal

A ustedes les quedó solamente a la salida la clasificación sin tener asociada la constante.

3) En la función cargarArchivo podrían tener un único fwrite al final y no dentro de cada case.

Son detalles, el trabajo está muy muy bien ! =D
Sigan así ! Felicitaciones =)

@sabrivg @matiashamide @juliiig @inaaranza @AleSanj
