### ISSUE TITLE
ENTREGA DE TP 2

### ISSUE THREAD

**Issue by sabrivg** [inaaranza/2020_K2031_Grupo_3#5]
Solicito corrección del trabajo practico: @santiagoferreiros

**Comment by santiagoferreiros** [comment]
Estimados,

El trabajo está muy bien. Se adaptaron a la solución sugerida. Realicé las pruebas, están teniendo problemas con la pila y el uso de paréntesis. 

![image](https://user-images.githubusercontent.com/46604718/83974960-579bad80-a8c7-11ea-902a-ad1ebf9dce77.png)

Por lo que puedo ver, el problema está en que hacen el POP para ver el caracter de la cima de la pila, pero después lo vuelve a poner PUSH. Y eso no está bien, porque entonces la pila nunca se les va a vaciar. Siempre están agregando nuevos caracteres. 

La linea 53 está OK

    caracter=pop(&pila); //para pasarselo a cimapila

Probablemente la solución sea que eliminen la **línea 54 

 push(&pila,caracter);**

Por favor revisar esta parte y ya con esto lo tendrían resuelto. Lo que les está pasando es que está apilando todo y nunca hacen un POP sin hacer un push. Entonces, si pudiesen ver lo que hay en la pila sería algo así : RR$$R$R$R$R$$$RR$RR$

Por darles un ejemplo,
Cualquier cosa me consulta,

El resto IMPECABLE ! =)

Saludos

@sabrivg @matiashamide @juliiig @inaaranza @AleSanj
