### ISSUE TITLE
ENTREGA TP4

### ISSUE THREAD

**Issue by sabrivg** [inaaranza/2020_K2031_Grupo_3#9]
terminamos el tp4 :)
@santiagoferreiros

**Comment by santiagoferreiros** [comment]
Estimado grupo, ¿Cómo están? Espero que bien

Les puedo pedir que en la entrega agreguen los archivos intermedios generados por flex, bison, como así también el archivo ejecutable? 

Muchas gracias!

Me avisan y vuelvo a revisar,

Saludos,

Santiago

**Comment by asanjinez** [comment]
Hola profe, ya estan subidos los archivos @santiagoferreiros

**Comment by santiagoferreiros** [comment]
Excelente trabajo equipo !

Nota: 9

El trabajo cumple con todos los requisitos pedidos en el enunciado. La gramática está acorde a los temas vistos en clase.
Felicitaciones! 

![image](https://user-images.githubusercontent.com/46604718/96901326-7e6b1280-1469-11eb-9d93-e9e8abc01181.png)

Gracias :)

Sigan trabajando así para el TPI

Vamos por más!
